seed: 147

# datamoduleで包含するので、datasetは不要
dataset:
  name: "SegmentationDataset"
  params:
    features_dir: "./data/raw/data/train_features"
    labels_dir: "./data/raw/data/train_labels"
    bands: ["B02.tif", "B03.tif", "B08.tif"]
# datamoduleで包含するので、datasetは不要

datamodule:
  name: "SegmentationDataModule"
  params:
    data_dir: "./data"
    bands: ["B02.tif", "B03.tif", "B08.tif"]
    gamma: 0.25
    batch_size: 16
    num_workers: 1
    train_holds: [0, 1, 2, 3, 4, 5, 6]
    val_holds: [7, 8]
    test_holds: [9]
    

model:
  name: "VanillaUnet"
  params:
    encoder_name: resnet34
    encoder_weights: imagenet
    in_channels: 3
    classes: 1
    encoder_depth: 3
    decoder_channels: [256, 64, 16]
    activation: sigmoid
    loss_func_name: BCELoss

trainer:
  name: Trainer
  params:
    max_epochs: 3
    accelerator: auto
