seed: 147

model:
  name: Six_Ch_One_Fig_EffNet_Deeplabv3p
  params:
    encoder_name: timm-efficientnet-b4
    encoder_depth: 5
    encoder_weights: imagenet
    classes: 1

train_test_ratio: 0.8
batch_size: 16

data:
  name: Tile_and_Just_Transform_Dataset
  params:
    images_directory: ../data/three_ch/train_data
    masks_directory: ../data/three_ch/mask_data
    train_transform: train_transforms_basic
    valid_transform: valid_transforms_basic
    num_of_tiles: 4

optimizer:
  name: Adam
  params:
    encoder_lr: !!float 1e-5
    decoder_lr: !!float 1e-4

criterion:
  name: BinaryFocalLoss
  params:
    gamma: 2.5
    alpha: 0.1                  # ターゲットに正の値が存在する事前確率

train:
  params:
    num_epochs: 100
    patience: 10
